#!/bin/bash
find . \( -name '*.o' -o -name '*~' -o -name '#*#' -o -name 'vgcore.*' -o -name '*.gch' \) -print0 | xargs -0 /bin/rm -f
find include/ \( -name '*~' -o -name '#*#' -o -name '*.gch' \) -print0 | xargs -0 /bin/rm -f
find source/ \( -name '*~' -o -name '#*#' -o -name 'vgcore.*' -o -name '*.gcda' -o -name '*.gcno' -o -name '*.gcov' \) -print0 | xargs -0 /bin/rm -f
find tests/ \( -name '*~' -o -name '#*#' -o -name '*.gcda' -o -name '*.gcno' -o -name '*.gcov' \) -print0 | xargs -0 /bin/rm -f
find lib/ \( -name '*~' -o -name '#*#' -o -name '*.gcda' -o -name '*.gcno' -o -name '*.a' \) -print0 | xargs -0 /bin/rm -f
