#!/bin/bash
find . \( -name '*.o' -o -name '*~' -o -name '#*#' -o -name '*.a' -o -name 'vgcore.*' -o -name '*.gch' -o -name '*.gcda' -o -name '*.gcno' -o -name '*.gcov' \) -print0 | xargs -0 /bin/rm -rf
